[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
optimizer = true
optimizer_runs = 1_000
ffi = true

libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = '0.8.24'
use_literal_content = true
extra_output = ["devdoc", "userdoc", "storagelayout"]
evm_version = 'london'
cache_path = 'cache_foundry'
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
line_length = 120
tab_width = 2
multiline_func_header = 'params_first'
bracket_spacing = true
int_types = 'preserve'

[profile.ci]
verbosity = 4

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 5_000

[profile.via-ir.fuzz]
runs = 1_000

[profile.min-solc]
solc_version = "0.8.4"

[profile.min-solc.fuzz]
runs = 1_000

[profile.min-solc-via-ir.fuzz]
runs = 1_000

[rpc_endpoints]
localhost = "http://localhost:8545"
ethereum = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
goerli = "https://ethereum-goerli.publicnode.com"
ronin-mainnet = "https://api-archived.roninchain.com/rpc"
ronin-testnet = "https://saigon-archive.roninchain.com/rpc"

[dependencies]
"@fdk" = { version = "0.3.0-beta", url = "https://github.com/axieinfinity/foundry-deployment-kit/archive/refs/tags/v0.3.0-beta.zip" }
"@prb-test" = { version = "0.6.4" }
"@openzeppelin" = { version = "4.7.3", url = "https://github.com/OpenZeppelin/openzeppelin-contracts/archive/refs/tags/v4.7.3.zip" }
"@chainlink-local" = { version = "0.2.2", url = "https://github.com/smartcontractkit/chainlink-local/archive/refs/tags/v0.2.2.zip" }